### ISSUE TITLE
"!googlecal today" does not load events

### ISSUE THREAD

**Issue by pu11em** [vranki/hemppa#1]
I have a google calendar filled in, with only all day events. I imported this calendar to googlecal and when I am using "!googlecal" i get the next 10 events from the bot, normally. This does not happen when I am using "!googlecal today".  

Screenshot 

![εικόνα](https://user-images.githubusercontent.com/57735348/71310160-8907e600-2419-11ea-9cf2-4cce250d48ba.png)

(2 tries)

**Comment by vranki** [comment]
Confirmed, I'm also seeing this on one of my rooms. Should be studied & fixed.

**Comment by vranki** [comment]
Should be fixed now. There was a silly bug in event handling.
