### ISSUE TITLE
Url: Youtube and Google services causing problem again with cookie consent page

### ISSUE THREAD

**Issue by vranki** [vranki/hemppa#129]
Youtube has added some kind of cookie consent page to video links, causing Title: Ennen kuin jatkat YouTubeen. Looks like we need to do some kind of exception to handle youtube separately.

**Comment by vranki** [comment]
huqa says he got titles working by sending CONSENT=YES -cookie with the request and not saving any cookies youtube sends.

Try that.

**Comment by huqa** [comment]
I just copied the cookie my desktop browser saved; pasting it here 
`"CONSENT=YES; Domain=.youtube.com; Path=/; SameSite=None; Secure; Expires=Sun, 10 Jan 2038 07:59:59 GMT; Max-Age=946080000"`

**Comment by vranki** [comment]
@huqa I couldn't get it to work. I tried two methods:

```python3
            cookies = httpx.Cookies()
            cookies.set('CONSENT', 'YES', domain='.youtube.com')
            return cookies
```
```python3
            return {'CONSENT': 'YES', 'Domain': '.youtube.com', 
                'Path': '/', 'SameSite' : 'None', 'Expires': 'Sun, 10 Jan 2038 07:59:59 GMT', 'Max-Age': '946080000'}
```
These are sent in request as described in https://www.python-httpx.org/quickstart/#cookies

Do you have any sample code I could try to run?

**Comment by huqa** [comment]
No not really, my title scraper is made in golang. 

I actually use this cookie in a 'Set-Cookie' HTTP header. Might be worth trying out setting a header in the request.

**Comment by vranki** [comment]
Thanks for the hint, I'll need to try that.

**Comment by vranki** [comment]
Works now!

For future reference, it's enough to lie user-agent is Curl. The cookies did nothing. Let's see until google decides to cause more trouble..
