### ISSUE TITLE
wa: return single result on one line

### ISSUE THREAD

**Issue by vranki** [vranki/hemppa#138]
Currently simple answers create multi-line reply message with a bullet. Change it to return the result on one line.

**Comment by xPMo** [comment]
Okay, two sample queries (one which gives two subpods, the other which gives one but has a meaningful title).

I'm leaning toward 4, or maybe 3. However, I'm usually on Element and I don't mind the longer messages.

---

**!wa airspeed of an unladen swallow**

Current Result:

> **Result**:
> - 25 mph (miles per hour)
> - (asked, but not answered, about a general swallow in the 1975 film Monty Python and the Holy Grail)

Proposed:

> 1. 25 mph (miles per hour)
> 1. 25 mph (miles per hour) (asked, but not answered, about a general swallow in the 1975 film Monty Python and the Holy Grail)
> 2. 25 mph (miles per hour) | (asked, but not answered, about a general swallow in the 1975 film Monty Python and the Holy Grail)
> 3. **Result**: 25 mph (miles per hour) | (asked, but not answered, about a general swallow in the 1975 film Monty Python and the Holy Grail)

---

**!wa prod (n=1 to 8) (n/2)**

Current Result:

> **Product**:
> - product_(n=1)^8 n/2 = 315/2

Proposed:

> 1. product_(n=1)^8 n/2 = 315/2
> 1. product_(n=1)^8 n/2 = 315/2
> 2. product_(n=1)^8 n/2 = 315/2
> 3. **Product**: product_(n=1)^8 n/2 = 315/2
