### ISSUE TITLE
Gfycat is broken

### ISSUE THREAD

**Issue by vranki** [vranki/hemppa#172]
Always returns something like: Sorry. Something went wrong fetching https://fat.gfycat.com/FreeMinorDiamondbackrattlesnake.gif and uploading it to the image to matrix server :(

**Comment by vranki** [comment]
@aspacca could you check this out? Looks like gfycat now needs API key and the queries return 403.

**Comment by aspacca** [comment]
@vranki it seems to be a transient error from gfycat that I've experienced as well

https://api.gfycat.com/v1/gfycats/search?search_text=omg
https://thumbs.gfycat.com/UniformScaryAnemone-size_restricted.gif
https://thumbs.gfycat.com/ThankfulUnsteadyAdouri-max-14mb.gif

did you test the word "test" as search query, by chance? so far I can reproduce regularly with it

**Comment by vranki** [comment]
Yes, I tested with "test". So you think it's a server side issue? If so, I don't think any action is needed. Maybe catch the exception and provide a nicer error message to user?

**Comment by aspacca** [comment]
the exception is already caught on https://github.com/vranki/hemppa/blob/fb3046b11eff6f679887bc68eda158273d9fcc0a/bot.py#L120

![image](https://transfer.sh/inline/ErkGSb/Schermata%202021-09-13%20alle%2008.54.02.png)

I can see the sentence makes no much sense :)
I should have time to send a PR to rephrase it later in the evening

**Comment by vranki** [comment]
Thanks! :-)

**Comment by aspacca** [comment]
done in #174
