### ISSUE TITLE
Element Thread Support

### ISSUE THREAD

**Issue by xPMo** [vranki/hemppa#192]
Threads are currently available in Labs. Without thread support, hemppa will reply to threaded messages in the primary channel:
![2022-01-25_22:11:43 hfV](https://user-images.githubusercontent.com/16061366/151102778-146b9913-d20e-411a-9d51-a83a39cb74b2.png)

Thread support would mean detecting the following structure in the event and adding a similar structure to the reply:

```json
    "m.relates_to": {
      "rel_type": "io.element.thread",
      "event_id": thread.event_id,
      "m.in_reply_to": {
        "event_id": previous_message.event_id,
        "m.render_in": [
          "io.element.thread"
        ]
      }
    }
```

**Comment by vranki** [comment]
Thanks, this should indeed be done. I hope it can be done with minimal changes to modules. Maybe give references to original event in send_text/send_html functions and reply to thread automatically. I haven't checked if the nio library has any support for this yet or does it need to be coded in the bot.

**Comment by xPMo** [comment]
Our `send_text`/`send_html` functions unfortunately don't have that context, just the room and not the instigating event. To not disturb modules, we would have to piggy-back either the whole event or the thread context onto the `room` structure, which smells bad.
