### ISSUE TITLE
RoomMemberEvent?

### ISSUE THREAD

**Issue by ser** [vranki/hemppa#2]
Hi, don't you think it would be very useful to allow bots to react to RoomMemberEvent as well?

**Comment by vranki** [comment]
Currently I don't have any use case for it. Can be added if it is needed for something.

**Comment by ser** [comment]
A simple use case is a bot which publicly welcomes a user when he/she enters a room. Would you accept a PR for such a simple bot?

**Comment by vranki** [comment]
Yes, but that module needs to be disabled by default. I'm planning to do a mechanism to disable modules with a command.

**Comment by ser** [comment]
GR8!

It could be cool to have possibility to selectively enable/disable modules in the main configuration as well.

**Comment by vranki** [comment]
Modules can subscribe to any events, including RoomMemberEvent and there is now mechanism to enable / disable modules. Closing this, just write the module.
