### ISSUE TITLE
split help message into multiple messages

### ISSUE THREAD

**Issue by ancho** [vranki/hemppa#44]
If the bot is in a bridged irc channel messages longer than four lines get greplaced with a long message link.

![long-message-irc](https://user-images.githubusercontent.com/264432/74386785-2c142500-4df7-11ea-9230-f8671b0b5ed0.png)

**Comment by vranki** [comment]
Actually currently it seems it sends help to IRC channels as separate lines. Maybe m.notice messages are not converted to URL? 
I got complaint of long !help text spamming IRC channel. I've shortened it a bit now, perhaps that's a good compromise. Closing this and the other issue. Reopen if needed.
