### ISSUE TITLE
Access token handling is broken

### ISSUE THREAD

**Issue by jcgruenhage** [vranki/hemppa#56]
When both the password and access token are provided, the handling of those is inconsistent.

 - When starting the bot, it first looks at the access token, if it's provided, it is used.
 - When stopping the bot, it first looks at the password, and if that is provided, it invalidates the token, *even when the token was provided externally*.

This causes the bot to work *once* when configured with both, after a restart it complains that the access token is invalid.

What should happen instead is a check that password and access token are mutually exclusive configuration options, so that the bot straight up refuses to start when both are provided.

If that is to drastic, you can alternatively straighten out the handling above, adding an additional check before logging out, which makes sure that a token is only invalidated when it was created by the bot.

Because this issue comes off as a bit negative: It's not meant negatively, I appreciate the work you've put into this! It's quite nice to see so many matrix bots.

**Comment by vranki** [comment]
Thanks for reporting. I removed whole support for password login as access token is the correct way to log in. I also removed logout functionality as it's also not needed.
