### ISSUE TITLE
Url getting nonetype

### ISSUE THREAD

**Issue by vranki** [vranki/hemppa#83]
Check this out, potential bot killer: module url - Failed parsing response from url https://i.imgur.com/3l0RtBs.jpg. Error: 'NoneType' object has no attribute 'string'

**Comment by tswfi** [comment]
Can't see how that would kill the bot. 

The log entry comes from here: https://github.com/vranki/hemppa/blob/master/modules/url.py#L122

and the reason is that title tag is not found at all here: https://github.com/vranki/hemppa/blob/master/modules/url.py#L117
