### ISSUE TITLE
Does hemppa work with encrypted rooms?

### ISSUE THREAD

**Issue by mcat-ee** [vranki/hemppa#87]
I've tried testing the !echo command with my instance of the hemppa bot but it only seems to reply in unencrypted rooms - is this a known limitation or have I screwed up some config?

Cases I've tried:
- Sending a message in an unencrypted chatroom - send !echo to the bot and it echoed the message
- Sending a message in an encrypted chatroom - no response to !echo message

I'm using the Synapse reference server and I've tested with Riot and RiotX clients on Android.

**Comment by ptman** [comment]
You can probably run hemppa through pantalaimon
