### ISSUE TITLE
Docker version fails due to missing pyyaml

### ISSUE THREAD

**Issue by vranki** [vranki/hemppa#92]
pyyaml is in Pipfile but it is not installed for some reason. Study and fix. Workaround: add line pip3 install pyyaml to Dockerfile

**Comment by berlincount** [comment]
Seems like https://pipenv.pypa.io/en/latest/changelog/#id16 has changed some things in a breaking way :-/

`2018.11.26` still works, `2020.5.28` already breaks, `latest`/`2020.6.2` doesn't work either.
